#!/usr/bin/env python3
"""Scan a pull request's own text for forbidden names and personal paths.

check_distribution.py scans tracked files.  The rule it enforces, that no
instructor or classmate is named, covers the pull request too: a title, a body
and every commit message land in the repository's permanent history, and a
squash merge folds the title and body into the one commit that reaches main.
Until this existed those were checked by hand, which is to say checked when
somebody remembered.

Two properties matter more than the scanning.

The text is hostile input.  A pull request body is written by whoever opened
it, so it is never interpolated into a shell command: GitHub puts it in the
environment, this reads os.environ, and git runs through an argument list.
A body containing a backtick or a dollar-paren is inert text here, and
tests/test_pr_text_scan.py proves that rather than asserting it.

A finding is never printed.  The build log is the wrong place to publish the
name the scan exists to keep out, so a hit reports which text it was in and
where, and the person reading the log goes and looks.
"""
from pathlib import Path
import os, subprocess, sys

sys.path.insert(0, str(Path(__file__).resolve().parent))
from check_distribution import NAMES_ENV, forbidden_names_from_env, text_findings


def commit_messages(base, head, repo=None):
    """Every commit message in the pull request, oldest first.

    Merges are skipped: a merge commit's message is generated by GitHub and
    names nobody, while its diff belongs to the commits already listed.
    """
    if not base or not head:
        raise ValueError(
            "the base and head commits of the pull request are both required; "
            "without them there is no range to scan"
        )
    # An argument list, never a shell string: base and head arrive from the
    # event payload, and a shell would parse them.
    result = subprocess.run(
        # --reverse so "commit message 2" counts the way a reader of the pull
        # request counts, oldest first, rather than git's newest-first default.
        ["git", "log", "--format=%B%x00", "--no-merges", "--reverse", f"{base}..{head}"],
        cwd=str(repo) if repo else None,
        capture_output=True, text=True, check=False,
    )
    if result.returncode != 0:
        raise ValueError(
            f"cannot read the commit range {base}..{head}: {result.stderr.strip()}. "
            "Check out with fetch-depth: 0 so the history is present."
        )
    return [message for message in result.stdout.split("\0") if message.strip()]


def scan(title, body, messages, names):
    """Return a problem line for every piece of text that has a finding."""
    texts = [("title", title or ""), ("body", body or "")]
    texts += [(f"commit message {i}", m) for i, m in enumerate(messages, start=1)]
    problems = []
    for where, text in texts:
        for kind, offset in text_findings(text, names):
            # The name itself is deliberately absent.  Position is enough to
            # find it, and a log is a place a name does not come back from.
            problems.append(f"{kind} in the pull request {where} at offset {offset}")
    # A list holding both a full name and the bare surname matches one
    # occurrence twice, at the same place.  Two identical lines read as a bug
    # in the scanner and say nothing the first does not.
    return list(dict.fromkeys(problems))


def main(argv=None, environ=None):
    environ = os.environ if environ is None else environ
    try:
        names = forbidden_names_from_env(environ)
    except ValueError as exc:
        print(exc, file=sys.stderr)
        return 2

    # Fail closed, both times.  A scan that skips itself and reports success
    # is the failure this step was added to remove, so an unset secret is an
    # error rather than a quiet pass.  On a pull request from a fork GitHub
    # withholds secrets, so this is what a fork PR will hit: it cannot be
    # scanned, and it is refused rather than waved through.
    if not names:
        print(
            f"::error::{NAMES_ENV} is not set, so the pull request text was not scanned. "
            "If this is a pull request from a fork, GitHub does not pass secrets to it "
            "and it cannot be scanned here; push the branch to this repository instead.",
            file=sys.stderr,
        )
        return 1

    try:
        messages = commit_messages(environ.get("BASE_SHA"), environ.get("HEAD_SHA"))
    except ValueError as exc:
        print(f"::error::{exc}", file=sys.stderr)
        return 1

    # Zero commits means the range was wrong, not that a pull request is
    # empty.  Reporting "clean" for text nobody read is the same lie as
    # skipping the scan.
    if not messages:
        print(
            "::error::no commit messages were found in this pull request, so nothing "
            "was scanned. The commit range is wrong or the history is shallow.",
            file=sys.stderr,
        )
        return 1

    problems = scan(environ.get("PR_TITLE"), environ.get("PR_BODY"), messages, names)
    count = f"1 title, 1 body, {len(messages)} commit message{'s' * (len(messages) != 1)}"
    if problems:
        for problem in problems:
            print(f"::error::{problem}", file=sys.stderr)
        print(
            f"scanned {count} against {len(names)} names, "
            f"{len(problems)} problem{'s' * (len(problems) != 1)} found",
            file=sys.stderr,
        )
        return 1
    print(f"scanned {count} against {len(names)} names, clean")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
